name: Linux Actions
run-name: GitHub Actions by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  Go-Build-on-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache-dependency-path: "**/*.sum"

      - name: Build Go application
        run: 
          cd ${{ github.workspace }}/gitlab/create_user
          mkdir -p ${{ github.workspace }}/my-golang-tools-linux
          for file in $(find . -type f -name '*.go'); do
            go build -v "$file" -o "${{ github.workspace }}/my-golang-tools-linux/$(basename "${file%.go}")"
          done

      - name: 制品保存
        uses: actions/upload-artifact@v4
        with:
          name: my-golang-tools-linux