name: Linux Actions
run-name: GitHub Actions by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  Go-Build-on-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache-dependency-path: "**/*.sum"
      
      - name: Build Go application
        run: |
          pwd
          mkdir -p my-golang-tools-linux
          cd gitlab/cretae_user
          for file in $(find . -type f -name '*.go'); do
            echo "file:$file"
            go build -o "${{ github.workspace }}/$(basename ${file} | cut -d'.' -f1)" -v "$file" 
          done

      - name: 制品保存
        uses: actions/upload-artifact@v4
        with:
          name: my-golang-tools-linux